AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: D&D API - FastAPI application deployed to AWS Lambda

Parameters:
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: dnd-api
        ENVIRONMENT: !Ref Environment

Resources:
  DndApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "dnd-api-${Environment}"
      CodeUri: .
      Handler: app.lambda_handler.handler
      Description: !Sub "D&D API FastAPI Lambda function - ${Environment}"
      Architectures:
        - x86_64
      Events:
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Tags:
        Environment: !Ref Environment

Outputs:
  DndApi:
    Description: "API Gateway endpoint URL for D&D API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  DndApiFunction:
    Description: "D&D API Lambda Function ARN"
    Value: !GetAtt DndApiFunction.Arn
  DndApiFunctionIamRole:
    Description: "Implicit IAM Role created for D&D API function"
    Value: !GetAtt DndApiFunctionRole.Arn
  Environment:
    Description: "Deployment environment"
    Value: !Ref Environment
